// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using aYoTechTest.DAL.Classes;

#nullable disable

namespace aYoTechTest.DAL.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20221118143853_initial_database")]
    partial class initial_database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("aYoTechTest.Models.Entities.MeasuringUnit", b =>
                {
                    b.Property<int>("MeasuringUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeasuringUnitId"));

                    b.Property<DateTime?>("AuthorisedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuthorisedById")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedById")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("LastUpdatedById")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MetricUnitDesc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("text");

                    b.Property<byte>("UnitType")
                        .HasColumnType("smallint");

                    b.HasKey("MeasuringUnitId");

                    b.HasIndex("AuthorisedAt");

                    b.HasIndex("AuthorisedById");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("DeletedById");

                    b.HasIndex("LastUpdatedAt");

                    b.HasIndex("LastUpdatedById");

                    b.ToTable("MeasuringUnits");
                });

            modelBuilder.Entity("aYoTechTest.Models.Entities.SupportedConversion", b =>
                {
                    b.Property<int>("SupportedConversionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupportedConversionId"));

                    b.Property<DateTime?>("AuthorisedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuthorisedById")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("ConversionType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedById")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("LastUpdatedById")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Multiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0.0m);

                    b.Property<int>("SourceUnitId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SourceUnitValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(1m);

                    b.Property<int>("TargetUnitId")
                        .HasColumnType("integer");

                    b.HasKey("SupportedConversionId");

                    b.HasIndex("AuthorisedAt");

                    b.HasIndex("AuthorisedById");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("DeletedById");

                    b.HasIndex("LastUpdatedAt");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("SourceUnitId");

                    b.HasIndex("SourceUnitValue");

                    b.HasIndex("TargetUnitId");

                    b.ToTable("SupportedConversions");
                });
#pragma warning restore 612, 618
        }
    }
}
